[package]
name = "basics_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
overflow-checks = false
# debug = false

# [profile.release]
# debug = false

[dependencies]
