name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "examples/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "examples/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install dependencies 🔧
        run: make install

      - name: Build 🏗️
        run: make build

      - name: Deploy to GitHub Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book